In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import re
import transformers

# Data Exploration

In [2]:
df = pd.read_csv("../Static Data/indeed.csv")
df.head()

,Job Title,Job Description,Job Type,Categories,Location,City,State,Country,Zip Code,Address,...,Employer Phone,Employer Logo,Companydescription,Employer Location,Employer City,Employer State,Employer Country,Employer Zip Code,Uniq Id,Crawl Timestamp
0,Shift Manager,"<div id=""jobDescriptionText"" class=""jobsearch-...",NaN,NaN,"Mission Hills, CA 91345",Mission Hills,CA,United States,91345,NaN,...,NaN,https://d2q79iu7y748jz.cloudfront.net/s/_squar...,Del Taco is an American quick service restaura...,"Mission Hills, CA 91345",Mission Hills,CA,United States,91345.0,511f9a53920f4641d701d51d3589349f,2019-08-24 09:13:18 +0000
1,Operations Support Manager,"<div id=""jobDescriptionText"" class=""jobsearch-...",NaN,NaN,"Atlanta, GA 30342",Atlanta,GA,United States,30342,NaN,...,NaN,https://d2q79iu7y748jz.cloudfront.net/s/_logo/...,"Based in Atlanta, FOCUS Brands Inc. is an inno...",NaN,NaN,NaN,United States,NaN,4955daf0a3facbe2acb6c429ba394e6d,2019-09-19 08:16:55 +0000
2,Senior Product Manager - Data,"<div id=""jobDescriptionText"" class=""jobsearch-...",NaN,NaN,"Chicago, IL",Chicago,IL,United States,NaN,NaN,...,NaN,NaN,Vibes Corp. reputation was built and establish...,NaN,NaN,NaN,United States,NaN,a0e0d12df1571962b785f17f43ceae12,2019-09-18 02:13:10 +0000
3,Part-Time Office Concierge,"<div id=""jobDescriptionText"" class=""jobsearch-...",NaN,NaN,"Festus, MO",Festus,MO,United States,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,United States,NaN,56e411fd731f76ac916bf4fb169250e9,2019-10-24 16:39:13 +0000
4,Print & Marketing Associate,"<div id=""jobDescriptionText"" class=""jobsearch-...",NaN,NaN,"Cedar Rapids, IA 52404",Cedar Rapids,IA,United States,52404,NaN,...,NaN,https://d2q79iu7y748jz.cloudfront.net/s/_logo/...,"Staples is The Worklife Fulfillment Company, h...","Cedar Rapids, IA 52404",Cedar Rapids,IA,United States,52404.0,3fff5c0ad6981bf4bff6260bd5feab63,2019-08-24 22:29:10 +0000

In [3]:
list(df.columns)

['Job Title',
 'Job Description',
 'Job Type',
 'Categories',
 'Location',
 'City',
 'State',
 'Country',
 'Zip Code',
 'Address',
 'Salary From',
 'Salary To',
 'Salary Period',
 'Apply Url',
 'Apply Email',
 'Employees',
 'Industry',
 'Company Name',
 'Employer Email',
 'Employer Website',
 'Employer Phone',
 'Employer Logo',
 'Companydescription',
 'Employer Location',
 'Employer City',
 'Employer State',
 'Employer Country',
 'Employer Zip Code',
 'Uniq Id',
 'Crawl Timestamp']

In [4]:
df.shape

(999, 30)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 30 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Job Title           999 non-null    object
 1   Job Description     999 non-null    object
 2   Job Type            0 non-null      float64
 3   Categories          0 non-null      float64
 4   Location            999 non-null    object
 5   City                999 non-null    object
 6   State               999 non-null    object
 7   Country             999 non-null    object
 8   Zip Code            546 non-null    object
 9   Address             0 non-null      float64
 10  Salary From         0 non-null      float64
 11  Salary To           0 non-null      float64
 12  Salary Period       0 non-null      float64
 13  Apply Url           653 non-null    object
 14  Apply Email         0 non-null      float64
 15  Employees           0 non-null      float64
 16  Industry            0 non-null      float64
 17  Company Name        999 non-null    object
 18  Employer Email      0 non-null      float64
 19  Employer Website    0 non-null      float64
 20  Employer Phone      0 non-null      float64
 21  Employer Logo       644 non-null    object
 22  Companydescription  672 non-null    object
 23  Employer Location   95 non-null     object
 24  Employer City       95 non-null     object
 25  Employer State      95 non-null     object
 26  Employer Country    999 non-null    object
 27  Employer Zip Code   55 non-null     float64
 28  Uniq Id             999 non-null    object
 29  Crawl Timestamp     999 non-null    object
dtypes: float64(13), object(17)
memory usage: 234.3+ KB

# Get Text Data

In [6]:
df_text = df[['Job Title', 'Job Description']]
df_text.head()

,Job Title,Job Description
0,Shift Manager,"<div id=""jobDescriptionText"" class=""jobsearch-..."
1,Operations Support Manager,"<div id=""jobDescriptionText"" class=""jobsearch-..."
2,Senior Product Manager - Data,"<div id=""jobDescriptionText"" class=""jobsearch-..."
3,Part-Time Office Concierge,"<div id=""jobDescriptionText"" class=""jobsearch-..."
4,Print & Marketing Associate,"<div id=""jobDescriptionText"" class=""jobsearch-..."

In [7]:
# process Job Description
def process_html(txt):
    result = re.sub(".*?<.*?>","",txt)
    return result

In [8]:
sample_text = process_html(df_text['Job Description'][0])
print(sample_text)

WE ARE LOOKING FOR TOP PERFORMERS TO GROW WITH US!

Del Taco needs people with the ability to handle multiple responsibilities and deliver the quality and guest service that defines our brand. While we look for you to bring the right skills and personality for a Shift Manager position, we'll also provide the training and support you need to continue to grow and advance.

Our Shift Managers support our stores and General Managers in creating an amazing guest experience, and empowering their team to be at their very best. Our Shift Managers create a culture in our restaurants that is exciting, optimistic and rewarding.

Del Taco Shift Managers have significant opportunities for growth and career advancement and are charged with supporting the General Manager with the tasks of training the next generation of leaders, guiding them to be promoted and empowering them to have a successful career.


Supports General Manager in supervising team that delivers effective results in the areas of quality, guest service, food cost, labor cost, safety, security, cleanliness and product preparation.
Running shifts and supporting the GM in managing the execution of all Company policies, procedures, programs and systems.
Ensures objectives are reached in all areas while following all Company guidelines.
Ensure compliance during shifts with all federal, state and local laws and ethical business practices.
Supports GM in creating and maintaining an "Employer of Choice" environment.
Supports GM in providing leadership, direction, training and development to the restaurant team.
Supports GM in supervising and directing the workforce.
Supporting GM in making staffing decisions such as, recommending interviews, and administering disciplinary action as needed.
Make recommendations to enhance restaurant operations.
Delivers effective results in the areas of quality, guest service, safety, security, cleanliness and product preparation.
Exhibits a cheerful and helpful manner
Demonstrates a complete understanding of our menu items and has the ability to explain them to guests accurately
Uses Point of Sale system/cash register to record orders and compute order amounts; collecting payment from guests
Understands and adheres to proper food handling, safety and sanitations standards
Ability to follow all Company operation policies, and procedures
Make recommendations to enhance restaurant operations.
Maintains a professional appearance and grooming standards


1-2 years of experience in quick service restaurant environment with demonstrated ability to ensure guest satisfaction and ability to train and maintain an on-going guest service delivery.
Demonstrated ability to be a leadership partner with management and staff, and to provide quality service to guests.
Demonstrated ability to handle multiple tasks with effective follow-through.
Demonstrated ability to motivate and lead staff to achieve organizational goals.
General knowledge of computers, POS systems, various electronic devices, and various software.
Ability to perform basic business math skills. Cash handling skills desired.
Excellent organizational skills for keeping detailed records, reports and logs.
Demonstrated ability to visually assess and evaluate safety hazards in the work place as mandated by company safety procedures. Ensure OSHA, local health and safety codes and company safety policies are met/followed.
Ability to communicate, develop and maintain a close, effective relationships colleagues, department managers, partners and the public.
Implement training and development plans and train staff
Ability to read, write and speak effectively in English.


Must possess a valid driverâ€™s license and proof of vehicle insurance.
1-2 years of experience in a Quick Service restaurant environment or a guest service industry in a supervisory or leadership role or an equivalent combination is preferred.
Food Handlers certification may be required
Ability to stand and walk for approximately 95-100% of shift including ability to bend, reach, and lift and carry a max of 50 pounds.
In Return we offer an excellent compensation and benefits package to include:

Great pay
Shift Leader Vacation Plan
Flexible Scheduling
All Shifts Available
Employee Assistance Program
401(k) Savings and Investment Plan with discretionary company match
To apply for this position, please click on â€œApply Nowâ€. Only qualified candidates will be considered.

The Company is fully committed to Equal Employment Opportunity and to attracting, retaining, developing and promoting the most qualified employees without regard to their race, gender, color, religion, sexual orientation, national origin, age, physical or mental disability, citizenship status, veteran status, or any other characteristic prohibited by federal or state law. We are dedicated to providing a work environment free from discrimination and harassment, and where employees are treated with respect and dignity.

High School diploma or equivalent
1 â€“ 2 years experience in QSR industry / full service concept or 1 â€“ 2 years experience within Del Taco system
Must possess a valid driverâ€™s license, insurance, and use personal vehicle to make bank deposits and travel to other restaurants/business locations as required
Fluent in English
Excellent Customer Service
Adhere to Company Policies and Procedures
Proven ability to lead and motivate a diverse team
Strong Communication and Teamwork Skills
Strong Organizational Skills
Detail Oriented and Accurate
Ability to work under pressure
Ability to Stand and Walk for 5-6 hours at a time
Ability to lift 25 Ibs

# Classification Model

https://huggingface.co/ml6team/keyphrase-extraction-kbir-inspec

In [9]:
from transformers import (
    TokenClassificationPipeline,
    AutoModelForTokenClassification,
    AutoTokenizer,
)
from transformers.pipelines import AggregationStrategy
import numpy as np

# Define keyphrase extraction pipeline
class KeyphraseExtractionPipeline(TokenClassificationPipeline):
    def __init__(self, model, *args, **kwargs):
        super().__init__(
            model=AutoModelForTokenClassification.from_pretrained(model),
            tokenizer=AutoTokenizer.from_pretrained(model),
            *args,
            **kwargs
        )

    def postprocess(self, all_outputs):
        results = super().postprocess(
            all_outputs=all_outputs,
            aggregation_strategy=AggregationStrategy.SIMPLE,
        )
        return np.unique([result.get("word").strip() for result in results])

# Load pipeline
model_name = "ml6team/keyphrase-extraction-kbir-inspec"
extractor = KeyphraseExtractionPipeline(model=model_name)

In [10]:
keyphrases = extractor(sample_text)

print(keyphrases)

['Company operation policies' 'Del Taco' 'GM' 'General Manager'
 'Shift Manager' 'career advancement' 'cleanliness' 'compliance'
 'disciplinary action' 'food cost' 'food handling' 'guest service'
 'labor cost' 'product preparation' 'quick service restaurant environment'
 'safety' 'sanitations standards' 'security']

In [18]:
tokenizer=AutoTokenizer.from_pretrained(model_name)
tokenizer.encode(sample_text)

Token indices sequence length is longer than the specified maximum sequence length for this model (1167 > 512). Running this sequence through the model will result in indexing errors

[0,
 10284,
 10616,
 33584,
 1862,
 5089,
 17918,
 18578,
 38036,
 4322,
 3842,
 8837,
 4581,
 17345,
 382,
 328,
 50121,
 50118,
 50121,
 50118,
 21502,
 23206,
 782,
 82,
 19,
 5,
 1460,
 7,
 3679,
 1533,
 9582,
 8,
 2438,
 5,
 1318,
 8,
 4910,
 544,
 14,
 19857,
 84,
 1518,
 4,
 616,
 52,
 356,
 13,
 47,
 7,
 836,
 5,
 235,
 2417,
 8,
 6718,
 13,
 10,
 36790,
 4827,
 737,
 6,
 52,
 581,
 67,
 694,
 5,
 1058,
 8,
 323,
 47,
 240,
 7,
 535,
 7,
 1733,
 8,
 3316,
 4,
 50121,
 50118,
 50121,
 50118,
 2522,
 36790,
 1554,
 14979,
 323,
 84,
 2326,
 8,
 1292,
 1554,
 14979,
 11,
 2351,
 41,
 2770,
 4910,
 676,
 6,
 8,
 18503,
 49,
 165,
 7,
 28,
 23,
 49,
 182,
 275,
 4,
 1541,
 36790,
 1554,
 14979,
 1045,
 10,
 2040,
 11,
 84,
 4329,
 14,
 16,
 3571,
 6,
 7168,
 8,
 16044,
 4,
 50121,
 50118,
 50121,
 50118,
 21502,
 23206,
 36790,
 1554,
 14979,
 33,
 1233,
 1616,
 13,
 434,
 8,
 756,
 19026,
 8,
 32,
 1340,
 19,
 3117,
 5,
 1292,
 4827,
 19,
 5,
 8558,
 9,
 1058,
 5,
 220,
 2706,
 9,
 917,
 6,
 17769,
 106,
 7,
 28,
 7715,
 8,
 18503,
 106,
 7,
 33,
 10,
 1800,
 756,
 4,
 50121,
 50118,
 50121,
 50118,
 50121,
 50118,
 33661,
 8807,
 1292,
 4827,
 11,
 21291,
 3009,
 165,
 14,
 8806,
 2375,
 775,
 11,
 5,
 911,
 9,
 1318,
 6,
 4910,
 544,
 6,
 689,
 701,
 6,
 4178,
 701,
 6,
 1078,
 6,
 573,
 6,
 2382,
 24060,
 8,
 1152,
 7094,
 4,
 50121,
 50118,
 42900,
 10701,
 8,
 3117,
 5,
 5323,
 11,
 4196,
 5,
 7356,
 9,
 70,
 1260,
 1986,
 6,
 6196,
 6,
 1767,
 8,
 1743,
 4,
 50121,
 50118,
 16040,
 29,
 4123,
 10366,
 32,
 1348,
 11,
 70,
 911,
 150,
 511,
 70,
 1260,
 6401,
 4,
 50121,
 50118,
 16040,
 41404,
 6265,
 148,
 10701,
 19,
 70,
 752,
 6,
 194,
 8,
 400,
 2074,
 8,
 13557,
 265,
 3464,
 4,
 50121,
 50118,
 33661,
 8807,
 5323,
 11,
 2351,
 8,
 6780,
 41,
 22,
 38031,
 254,
 9,
 14431,
 113,
 1737,
 4,
 50121,
 50118,
 33661,
 8807,
 5323,
 11,
 1976,
 1673,
 6,
 2698,
 6,
 1058,
 8,
 709,
 7,
 5,
 2391,
 165,
 4,
 50121,
 50118,
 33661,
 8807,
 5323,
 11,
 21291,
 3009,
 8,
 13062,
 5,
 6862,
 4,
 50121,
 50118,
 38873,
 154,
 5323,
 11,
 442,
 15996,
 2390,
 215,
 25,
 6,
 22190,
 5533,
 6,
 8,
 33742,
 13999,
 814,
 25,
 956,
 4,
 50121,
 50118,
 18114,
 4664,
 7,
 6292,
 2391,
 1414,
 4,
 50121,
 50118,
 21502,
 10744,
 2375,
 775,
 11,
 5,
 911,
 9,
 1318,
 6,
 4910,
 544,
 6,
 1078,
 6,
 573,
 6,
 2382,
 24060,
 8,
 1152,
 7094,
 4,
 50121,
 50118,
 9089,
 25068,
 2629,
 10,
 33928,
 8,
 7163,
 4737,
 50121,
 50118,
 44542,
 6031,
 1626,
 10,
 1498,
 2969,
 9,
 84,
 5765,
 1964,
 8,
 34,
 5,
 1460,
 7,
 3922,
 106,
 7,
 3958,
 12775,
 50121,
 50118,
 16419,
 293,
 4937,
 9,
 9140,
 467,
 73,
 20122,
 5124,
 7,
 638,
 3365,
 8,
 37357,
 645,
 5353,
 131,
 8664,
 3207,
 31,
 3958,
 50121,
 50118,
 17245,
 8490,
 29,
 8,
 2329,
 29492,
 7,
 4692,
 689,
 5516,
 6,
 1078,
 8,
 15610,
 29148,
 2820,
 50121,
 50118,
 47685,
 7,
 1407,
 70,
 1260,
 2513,
 1986,
 6,
 8,
 6196,
 50121,
 50118,
 18114,
 4664,
 7,
 6292,
 2391,
 1414,
 4,
 50121,
 50118,
 448,
 12042,
 5069,
 10,
 2038,
 2772,
 8,
 26925,
 2820,
 50121,
 50118,
 50121,
 50118,
 50121,
 50118,
 134,
 12,
 176,
 107,
 9,
 676,
 11,
 2119,
 544,
 2391,
 1737,
 19,
 7646,
 1460,
 7,
 1306,
 4910,
 11658,
 8,
 1460,
 7,
 2341,
 8,
 3014,
 41,
 15,
 12,
 12891,
 4910,
 544,
 2996,
 4,
 50121,
 50118,
 44542,
 6031,
 1070,
 1460,
 7,
 28,
 10,
 1673,
 1784,
 19,
 1052,
 8,
 813,
 6,
 8,
 7,
 694,
 1318,
 544,
 7,
 3958,
 4,
 50121,
 50118,
 44542,
 6031,
 1070,
 1460,
 7,
 3679,
 1533,
 8558,
 19,
 2375,
 1407,
 12,
 11672,
 4,
 50121,
 50118,
 44542,
 6031,
 1070,
 1460,
 7,
 22962,
 8,
 483,
 813,
 7,
 3042,
 20973,
 1175,
 4,
 50121,
 50118,
 9344,
 2655,
 9,
 7796,
 6,
 29206,
 1743,
 6,
 1337,
 5175,
 2110,
 6,
 8,
 1337,
 2257,
 4,
 50121,
 50118,
 47685,
 7,
 3008,
 3280,
 265,
 10638,
 2417,
 4,
 7871,
 5516,
 2417,
 12762,
 4,
 50121,
 50118,
 46887,
 20973,
 2417,
 13,
 2396,
 4271,
 2189,
 6,
 690,
 8,
 24113,
 4,
 50121,
 50118,
 44542,
 6031,
 1070,
 1460,
 7,
 21545,
 7118,
 8,
 10516,
 1078,
 21125,
 11,
 5,
 173,
 317,
 25,
 17171,
 30,
 138,
 1078,
 6196,
 4,
 38141,
 8192,
 6826,
 6,
 400,
 474,
 8,
 1078,
 14284,
 8,
 138,
 1078,
 1986,
 32,
 1145,
 73,
 28481,
 196,
 4,
 50121,
 50118,
 47685,
 7,
 8469,
 6,
 2179,
 8,
 3014,
 10,
 593,
 6,
 2375,
 4158,
 4025,
 6,
 1494,
 4389,
 6,
 2567,
 8,
 5,
 285,
 4,
 50121,
 50118,
 20470,
 40224,
 1058,
 8,
 709,
 708,
 8,
 2341,
 813,
 50121,
 50118,
 47685,
 7,
 1166,
 6,
 3116,
 8,
 1994,
 4296,
 11,
 2370,
 4,
 50121,
 50118,
 50121,
 50118,
 50121,
 50118,
 41033,
 15256,
 10,
 8218,
 1393,
 3695,
 10851,
 13445,
 29,
 4385,
 8,
 6461,
 9,
 1155,
 1911,
 4,
 50121,
 50118,
 134,
 12,
 176,
 107,
 9,
 676,
 11,
 10,
 13287,
 1841,
 2391,
 1737,
 50,
 10,
 4910,
 544,
 539,
 11,
 10,
 2422,
 20946,
 50,
 1673,
 774,
 50,
 41,
 6305,
 4069,
 16,
 6813,
 4,
 50121,
 50118,
 29337,
 7406,
 7906,
 12930,
 189,
 28,
 1552,
 50121,
 50118,
 47685,
 7,
 1413,
 8,
 1656,
 13,
 2219,
 6164,
 12,
 1866,
 207,
 9,
 3294,
 217,
 1460,
 7,
 20789,
 6,
 1338,
 6,
 8,
 5258,
 8,
 2324,
 10,
 19220,
 9,
 654,
 2697,
 4,
 50121,
 50118,
 1121,
 11968,
 52,
 904,
 41,
 4206,
 4660,
 8,
 1795,
 3737,
 7,
 680,
 35,
 50121,
 50118,
 50121,
 50118,
 19065,
 582,
 50121,
 50118,
 45161,
 5337,
 20271,
 1258,
 5427,
 50121,
 50118,
 597,
 14726,
 4748,
 29527,
 17556,
 50121,
 50118,
 3684,
 840,
 22833,
 17175,
 50121,
 50118,
 38031,
 1942,
 19418,
 4928,
 50121,
 50118,
 33871,
 1640,
 330,
 43,
 26244,
 8,
 2830,
 5427,
 19,
 25159,
 138,
 914,
 50121,
 50118,
 3972,
 3253,
 13,
 42,
 737,
 6,
 2540,
 3753,
 15,
 952,
 7258,
 10851,
 1277,
 9085,
 47456,
 978,
 3695,
 10851,
 4056,
 46,
 4,
 4041,
 6048,
 2261,
 40,
 28,
 1687,
 4,
 50121,
 50118,
 50121,
 50118,
 133,
 1260,
 16,
 1950,
 2021,
 7,
 25235,
 17820,
 19469,
 8,
 7,
 13224,
 6,
 17784,
 6,
 2623,
 8,
 6061,
 5,
 144,
 6048,
 1321,
 396,
 6203,
 7,
 49,
 1015,
 6,
 3959,
 6,
 3195,
 6,
 6825,
 6,
 1363,
 14497,
 6,
 632,
 9813,
 6,
 1046,
 6,
 2166,
 50,
 2536,
 11096,
 6,
 8860,
 2194,
 6,
 3142,
 2194,
 6,
 50,
 143,
 97,
 26293,
 9986,
 30,
 752,
 50,
 194,
 488,
 4,
 166,
 32,
 3688,
 7,
 1976,
 10,
 173,
 1737,
 481,
 31,
 6886,
 8,
 4331,
 6,
 8,
 147,
 1321,
 32,
 3032,
 19,
 ...]

In [17]:
# encode the sample_text using distilbert

import torch

from transformers import AutoTokenizer, AutoModelForSequenceClassification

# Load the tokenizer and model  

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

model = AutoModelForSequenceClassification.from_pretrained("distilbert-base-uncased")

tokenizer.encode(sample_text)

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['pre_classifier.weight', 'classifier.bias', 'classifier.weight', 'pre_classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Token indices sequence length is longer than the specified maximum sequence length for this model (983 > 512). Running this sequence through the model will result in indexing errors

[101,
 2057,
 2024,
 2559,
 2005,
 2327,
 9567,
 2000,
 4982,
 2007,
 2149,
 999,
 3972,
 11937,
 3597,
 3791,
 2111,
 2007,
 1996,
 3754,
 2000,
 5047,
 3674,
 10198,
 1998,
 8116,
 1996,
 3737,
 1998,
 4113,
 2326,
 2008,
 11859,
 2256,
 4435,
 1012,
 2096,
 2057,
 2298,
 2005,
 2017,
 2000,
 3288,
 1996,
 2157,
 4813,
 1998,
 6180,
 2005,
 1037,
 5670,
 3208,
 2597,
 1010,
 2057,
 1005,
 2222,
 2036,
 3073,
 1996,
 2731,
 1998,
 2490,
 2017,
 2342,
 2000,
 3613,
 2000,
 4982,
 1998,
 5083,
 1012,
 2256,
 5670,
 10489,
 2490,
 2256,
 5324,
 1998,
 2236,
 10489,
 1999,
 4526,
 2019,
 6429,
 4113,
 3325,
 1010,
 1998,
 7861,
 23948,
 2037,
 2136,
 2000,
 2022,
 2012,
 2037,
 2200,
 2190,
 1012,
 2256,
 5670,
 10489,
 3443,
 1037,
 3226,
 1999,
 2256,
 7884,
 2008,
 2003,
 10990,
 1010,
 21931,
 1998,
 10377,
 2075,
 1012,
 3972,
 11937,
 3597,
 5670,
 10489,
 2031,
 3278,
 6695,
 2005,
 3930,
 1998,
 2476,
 12607,
 1998,
 2024,
 5338,
 2007,
 4637,
 1996,
 2236,
 3208,
 2007,
 1996,
 8518,
 1997,
 2731,
 1996,
 2279,
 4245,
 1997,
 4177,
 1010,
 14669,
 2068,
 2000,
 2022,
 3755,
 1998,
 7861,
 23948,
 2068,
 2000,
 2031,
 1037,
 3144,
 2476,
 1012,
 6753,
 2236,
 3208,
 1999,
 21238,
 2136,
 2008,
 18058,
 4621,
 3463,
 1999,
 1996,
 2752,
 1997,
 3737,
 1010,
 4113,
 2326,
 1010,
 2833,
 3465,
 1010,
 4450,
 3465,
 1010,
 3808,
 1010,
 3036,
 1010,
 4550,
 20942,
 1998,
 4031,
 7547,
 1012,
 2770,
 12363,
 1998,
 4637,
 1996,
 13938,
 1999,
 6605,
 1996,
 7781,
 1997,
 2035,
 2194,
 6043,
 1010,
 8853,
 1010,
 3454,
 1998,
 3001,
 1012,
 21312,
 11100,
 2024,
 2584,
 1999,
 2035,
 2752,
 2096,
 2206,
 2035,
 2194,
 11594,
 1012,
 5676,
 12646,
 2076,
 12363,
 2007,
 2035,
 2976,
 1010,
 2110,
 1998,
 2334,
 4277,
 1998,
 12962,
 2449,
 6078,
 1012,
 6753,
 13938,
 1999,
 4526,
 1998,
 8498,
 2019,
 1000,
 11194,
 1997,
 3601,
 1000,
 4044,
 1012,
 6753,
 13938,
 1999,
 4346,
 4105,
 1010,
 3257,
 1010,
 2731,
 1998,
 2458,
 2000,
 1996,
 4825,
 2136,
 1012,
 6753,
 13938,
 1999,
 21238,
 1998,
 9855,
 1996,
 14877,
 1012,
 4637,
 13938,
 1999,
 2437,
 3095,
 2075,
 6567,
 2107,
 2004,
 1010,
 16755,
 2075,
 7636,
 1010,
 1998,
 28965,
 17972,
 2895,
 2004,
 2734,
 1012,
 2191,
 11433,
 2000,
 11598,
 4825,
 3136,
 1012,
 18058,
 4621,
 3463,
 1999,
 1996,
 2752,
 1997,
 3737,
 1010,
 4113,
 2326,
 1010,
 3808,
 1010,
 3036,
 1010,
 4550,
 20942,
 1998,
 4031,
 7547,
 1012,
 10637,
 1037,
 18350,
 1998,
 14044,
 5450,
 16691,
 1037,
 3143,
 4824,
 1997,
 2256,
 12183,
 5167,
 1998,
 2038,
 1996,
 3754,
 2000,
 4863,
 2068,
 2000,
 6368,
 14125,
 3594,
 2391,
 1997,
 5096,
 2291,
 1013,
 5356,
 4236,
 2000,
 2501,
 4449,
 1998,
 24134,
 2344,
 8310,
 1025,
 9334,
 7909,
 2013,
 6368,
 19821,
 1998,
 25276,
 2015,
 2000,
 5372,
 2833,
 8304,
 1010,
 3808,
 1998,
 18723,
 2015,
 4781,
 3754,
 2000,
 3582,
 2035,
 2194,
 3169,
 6043,
 1010,
 1998,
 8853,
 2191,
 11433,
 2000,
 11598,
 4825,
 3136,
 1012,
 9319,
 1037,
 2658,
 3311,
 1998,
 18087,
 2075,
 4781,
 1015,
 1011,
 1016,
 2086,
 1997,
 3325,
 1999,
 4248,
 2326,
 4825,
 4044,
 2007,
 7645,
 3754,
 2000,
 5676,
 4113,
 9967,
 1998,
 3754,
 2000,
 3345,
 1998,
 5441,
 2019,
 2006,
 1011,
 2183,
 4113,
 2326,
 6959,
 1012,
 7645,
 3754,
 2000,
 2022,
 1037,
 4105,
 4256,
 2007,
 2968,
 1998,
 3095,
 1010,
 1998,
 2000,
 3073,
 3737,
 2326,
 2000,
 6368,
 1012,
 7645,
 3754,
 2000,
 5047,
 3674,
 8518,
 2007,
 4621,
 3582,
 1011,
 2083,
 1012,
 7645,
 3754,
 2000,
 9587,
 29068,
 3686,
 1998,
 2599,
 3095,
 2000,
 6162,
 13296,
 3289,
 1012,
 2236,
 3716,
 1997,
 7588,
 1010,
 13433,
 2015,
 3001,
 1010,
 2536,
 4816,
 5733,
 1010,
 1998,
 2536,
 4007,
 1012,
 3754,
 2000,
 4685,
 3937,
 2449,
 8785,
 4813,
 1012,
 5356,
 8304,
 4813,
 9059,
 1012,
 6581,
 13296,
 4813,
 2005,
 4363,
 6851,
 2636,
 1010,
 4311,
 1998,
 15664,
 1012,
 7645,
 3754,
 2000,
 17453,
 14358,
 1998,
 16157,
 3808,
 22010,
 1999,
 1996,
 2147,
 2173,
 2004,
 16714,
 2011,
 2194,
 3808,
 8853,
 1012,
 5676,
 9808,
 3270,
 1010,
 2334,
 2740,
 1998,
 3808,
 9537,
 1998,
 2194,
 3808,
 6043,
 2024,
 2777,
 1013,
 2628,
 1012,
 3754,
 2000,
 10639,
 1010,
 4503,
 1998,
 5441,
 1037,
 2485,
 1010,
 4621,
 6550,
 8628,
 1010,
 2533,
 10489,
 1010,
 5826,
 1998,
 1996,
 2270,
 1012,
 10408,
 2731,
 1998,
 2458,
 3488,
 1998,
 3345,
 3095,
 3754,
 2000,
 3191,
 1010,
 4339,
 1998,
 3713,
 6464,
 1999,
 2394,
 1012,
 2442,
 10295,
 1037,
 9398,
 4062,
 2050,
 30102,
 30108,
 2015,
 6105,
 1998,
 6947,
 1997,
 4316,
 5427,
 1012,
 1015,
 1011,
 1016,
 2086,
 1997,
 3325,
 1999,
 1037,
 4248,
 2326,
 4825,
 4044,
 2030,
 1037,
 4113,
 2326,
 3068,
 1999,
 1037,
 26653,
 2030,
 4105,
 2535,
 2030,
 2019,
 5662,
 5257,
 2003,
 6871,
 1012,
 2833,
 28213,
 2015,
 10618,
 2089,
 2022,
 3223,
 3754,
 2000,
 3233,
 1998,
 3328,
 2005,
 3155,
 5345,
 1011,
 2531,
 1003,
 1997,
 5670,
 2164,
 3754,
 2000,
 8815,
 1010,
 3362,
 1010,
 1998,
 6336,
 1998,
 4287,
 1037,
 4098,
 1997,
 2753,
 7038,
 1012,
 1999,
 2709,
 2057,
 3749,
 2019,
 6581,
 9430,
 1998,
 6666,
 7427,
 2000,
 2421,
 1024,
 2307,
 3477,
 5670,
 3003,
 10885,
 2933,
 12379,
 19940,
 2035,
 12363,
 2800,
 7904,
 5375,
 2565,
 22649,
 1006,
 1047,
 1007,
 10995,
 1998,
 5211,
 2933,
 2007,
 19258,
 5649,
 2194,
 2674,
 2000,
 6611,
 2005,
 2023,
 2597,
 1010,
 3531,
 11562,
 2006,
 1037,
 30102,
 29674,
 29098,
 2135,
 2085,
 2050,
 30102,
 1012,
 2069,
 4591,
 5347,
 2097,
 2022,
 2641,
 1012,
 1996,
 2194,
 2003,
 3929,
 5462,
 2000,
 5020,
 6107,
 4495,
 1998,
 2000,
 15411,
 1010,
 12823,
 1010,
 4975,
 1998,
 7694,
 1996,
 2087,
 4591,
 5126,
 2302,
 7634,
 2000,
 2037,
 2679,
 1010,
 5907,
 1010,
 3609,
 1010,
 4676,
 1010,
 4424,
 10296,
 1010,
 2120,
 4761,
 1010,
 2287,
 1010,
 3558,
 2030,
 5177,
 11980,
 1010,
 9068,
 3570,
 1010,
 8003,
 3570,
 1010,
 2030,
 2151,
 2060,
 8281,
 10890,
 2011,
 2976,
 2030,
 2110,
 2375,
 1012,
 2057,
 2024,
 4056,
 2000,
 4346,
 1037,
 2147,
 4044,
 2489,
 2013,
 9147,
 1998,
 16011,
 1010,
 1998,
 2073,
 5126,
 2024,
 5845,
 2007,
 4847,
 1998,
 13372,
 1012,
 2152,
 2082,
 9827,
 2030,
 5662,
 1015,
 1037,
 30102,
 1523,
 1016,
 2086,
 3325,
 1999,
 1053,
 21338,
 3068,
 1013,
 2440,
 2326,
 4145,
 2030,
 1015,
 1037,
 30102,
 1523,
 1016,
 2086,
 3325,
 2306,
 3972,
 11937,
 3597,
 2291,
 2442,
 10295,
 1037,
 9398,
 4062,
 2050,
 30102,
 30108,
 2015,
 6105,
 1010,
 5427,
 1010,
 1998,
 2224,
 3167,
 4316,
 2000,
 2191,
 2924,
 10042,
 1998,
 3604,
 2000,
 2060,
 7884,
 1013,
 2449,
 5269,
 2004,
 3223,
 19376,
 1999,
 2394,
 6581,
 8013,
 2326,
 25276,
 2000,
 2194,
 6043,
 1998,
 8853,
 10003,
 3754,
 2000,
 2599,
 1998,
 9587,
 29068,
 3686,
 1037,
 7578,
 2136,
 2844,
 4807,
 1998,
 2136,
 6198,
 4813,
 2844,
 13296,
 4813,
 6987,
 8048,
 1998,
 8321,
 3754,
 2000,
 2147,
 2104,
 3778,
 3754,
 2000,
 3233,
 1998,
 3328,
 2005,
 1019,
 1011,
 1020,
 2847,
 2012,
 1037,
 2051,
 3754,
 2000,
 6336,
 2423,
 21307,
 2015,
 102]